on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "main"

      - uses: TriPSs/conventional-changelog-action@v5
        id: changelog
        with:
          output-file: "false"
          skip-version-file: "true"
          github-token: ${{ secrets.github_token }}
          version-file: ".github/version.json"

      - name: Make build script executable
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: chmod +x ./build.sh

      - name: Run build script
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: ./build.sh ${{ steps.changelog.outputs.version }}

      - name: Create Release
        id: create_release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/hawk-auth-server-extension.jar
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true